### ISSUE TITLE
non able to write in firebase

### ISSUE THREAD

**Issue by RaniaProgramms** [Rupakpoddar/ESP8266Firebase#2]
This is what i got from the output :
Received String: }
Received int: 0
Received float: 0.00

I tried both method with/without fingerprint

**Comment by Rupakpoddar** [comment]
Hi @RaniaProgramms 
Can you share your code and the corresponding correct values in the database? 
Please replace your original project ID with something like 'XXXXXXX'.

**Comment by RaniaProgramms** [comment]
`/*
  Make sure your Firebase project's ".read" and ".write" rules are set to "true".
  Avoiding this will result in an error.
  For more details- https://github.com/Rupakpoddar/ESP8266Firebase/blob/master/README.md
*/

#include <ESP8266Firebase.h>
#include <ESP8266WiFi.h>

#define _SSID "TP-LINK_FBA9B0"        // Your WiFi SSID
#define _PASSWORD "88260464"    // Your WiFi Password
#define PROJECT_ID "XXXXXXXXX"   // Your Firebase Project ID. Can be found in project settings.

/*
  // FAST METHOD
  // REQUIRES PERIODIC UPDATE OF FINGERPRINT (EVERY 1 YEAR)
  // OUTDATED FINGERPRINT WILL STOP THE SERVICE
  // LATEST FINGERPRINT CAN BE FOUND AT- https://www.grc.com/fingerprints.htm?domain=test.firebaseio.com
  // REPLACE COLONS(:) WITH A SPACE(" ") AS SHOWN BELOW
  // 03:9E:4F:E6:83:FC:40:EF:FC:B2:C5:EF:36:0E:7C:3C:42:20:1B:8F ==> 03 9E 4F E6 83 FC 40 EF FC B2 C5 EF 36 0E 7C 3C 42 20 1B 8F
  #define FINGERPRINT "03 9E 4F E6 83 FC 40 EF FC B2 C5 EF 36 0E 7C 3C 42 20 1B 8F"
  Firebase firebase(PROJECT_ID, FINGERPRINT);
  // UNCOMMENT THIS BLOCK AND COMMENT THE LINE BELOW
*/

Firebase firebase(PROJECT_ID);    // SLOW BUT HASTLE-FREE METHOD FOR LONG TERM USAGE. DOES NOT REQUIRE PERIODIC UPDATE OF FINGERPRINT

void setup() {
  Serial.begin(115200);
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(1000);

  // Connect to WiFi
  Serial.println();
  Serial.println();
  Serial.print("Connecting to: ");
  Serial.println(_SSID);
  WiFi.begin(_SSID, _PASSWORD);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print("-");
  }

  Serial.println("");
  Serial.println("WiFi Connected");

  // Print the IP address
  Serial.print("Use this URL to connect: ");
  Serial.print("http://");
  Serial.print(WiFi.localIP());
  Serial.println("/");
  digitalWrite(LED_BUILTIN, HIGH);

//================================================================//
//================================================================//

  // Examples of setting String, integer and float values.
  firebase.setString("Example/setString", "It's Working");
  firebase.setInt("Example/setInt", 123);
  firebase.setFloat("Example/setFloat", 45.32);

  // Examples of pushing String, integer and float values.
  firebase.pushString("push", "Hello");
  firebase.pushInt("push", 789);
  firebase.pushFloat("push", 89.54);

  // Example of getting a String.
  String data1 = firebase.getString("Example/setString");
  Serial.print("Received String: ");
  Serial.println(data1);

  // Example of getting an int.
  int data2 = firebase.getInt("Example/setInt");
  Serial.print("Received int: ");
  Serial.println(data2);

  // Example of getting a float.
  float data3 = firebase.getFloat("Example/setFloat");
  Serial.print("Received float: ");
  Serial.println(data3);

  // Example of data deletion.
  //firebase.deleteData("Example");
}

void loop() {
  // Nothing
}
`

**Comment by Rupakpoddar** [comment]
Hi @RaniaProgramms
I apologise for the late reply. I can see you are using one of the example codes that I have provided. I encountered this same issue when I was using my university WiFi. The board was connecting to the internet but the university WiFi was automatically blocking all the requests made by the ESP device.

I tested out the same code with my mobile data hotspot and it worked instantly. I would recommend you to do the same. If the code works with mobile data hotspot then you should contact your internet service provider to get the issue fixed.

Again, make sure your Firebase project's ".read" and ".write" rules are set to "true".

Please let me know if you encounter any other issue. Thank you.

**Comment by bdrhnsen** [comment]
I have the same problem and connecting to hotspot does not solve the problem
![Ekran görüntüsü 2021-09-23 020117](https://user-images.githubusercontent.com/45562388/134433094-98c65e6a-830b-497d-b56e-eb40a8c5b2ef.png)
.

**Comment by Halcongala** [comment]
Hi @RaniaProgramms  , I had the same problem. The error is super easy to solve. Do not use PROJECT_ID that is contained in the configuration. Use the one that appears in the database as in the image that I attach.

Thanks @Rupakpoddar for all your work! You are amazing!! A lot of thanks! 
![Captura web_27-10-2021_](https://user-images.githubusercontent.com/72583205/139081592-61e7df8f-5d45-49ed-bebb-64b74c74af73.jpeg)

**Comment by Halcongala** [comment]
> I have the same problem and connecting to hotspot does not solve the problem ![Ekran görüntüsü 2021-09-23 020117](https://user-images.githubusercontent.com/45562388/134433094-98c65e6a-830b-497d-b56e-eb40a8c5b2ef.png) .

above the thread I already gave you the solution @bdrhnsen

**Comment by Rupakpoddar** [comment]
@Halcongala I am glad you figured out the issue. I hope it works for everybody. I would simply recommend to go to project settings and copy the project ID from there. The settings tab can be opened by clicking the small gear icon next to project overview on left side of the screen. I apologise for not responding; I am a college student and most of my time get consumed in doing the assignments. Other than that, I periodically keep testing the library and I go through the exact same procedure that a new user would have to go through so that I get to know about each and every issue that you might face. For now the library seems to be working fine. I am closing this thread.

**Comment by amitrao17** [comment]
> Hi @RaniaProgramms I apologise for the late reply. I can see you are using one of the example codes that I have provided. I encountered this same issue when I was using my university WiFi. The board was connecting to the internet but the university WiFi was automatically blocking all the requests made by the ESP device.
> 
> I tested out the same code with my mobile data hotspot and it worked instantly. I would recommend you to do the same. If the code works with mobile data hotspot then you should contact your internet service provider to get the issue fixed.
> 
> Again, make sure your Firebase project's ".read" and ".write" rules are set to "true".
> 
> Please let me know if you encounter any other issue. Thank you.

Hi Rupak,

I just changed ISP and my firebase code stopped working (note I am using Firebase-ESP8266 by Mozbit, not your library -- yet). Do you know specifically how your university WiFi was blocking firebase?

Thanks!
Amit
