### ISSUE TITLE
BSSL:read: failed

### ISSUE THREAD

**Issue by Afraim** [Rupakpoddar/ESP8266Firebase#4]
Dear Sir,
I just tried your library but I am getting a connection problem.

My code:
`/*
  Make sure your Firebase project's ".read" and ".write" rules are set to "true".
  Avoiding this will result in an error.
  For more details- https://github.com/Rupakpoddar/ESP8266Firebase/blob/master/README.md
*/

#include <ESP8266Firebase.h>
#include <ESP8266WiFi.h>

#define _SSID "Saadat"        // Your WiFi SSID
#define _PASSWORD "myloveismylord1234"    // Your WiFi Password
#define PROJECT_ID "arc-water-tank"   // Your Firebase Project ID. Can be found in project settings.
#define led D5
#define FINGERPRINT "4A 13 45 C9 71 9D CF A6 33 F1 F8 F0 1E 88 23 88 AC D6 2A 02"
/*
  // FAST METHOD
  // REQUIRES PERIODIC UPDATE OF FINGERPRINT (EVERY 1 YEAR)
  // OUTDATED FINGERPRINT WILL STOP THE SERVICE
  // LATEST FINGERPRINT CAN BE FOUND AT- https://www.grc.com/fingerprints.htm?domain=test.firebaseio.com
  // REPLACE COLONS(:) WITH A SPACE(" ") AS SHOWN BELOW
  // 03:9E:4F:E6:83:FC:40:EF:FC:B2:C5:EF:36:0E:7C:3C:42:20:1B:8F ==> 03 9E 4F E6 83 FC 40 EF FC B2 C5 EF 36 0E 7C 3C 42 20 1B 8F
  
  Firebase firebase(PROJECT_ID, FINGERPRINT);
  // UNCOMMENT THIS BLOCK AND COMMENT THE LINE BELOW
*/

Firebase firebase(PROJECT_ID, FINGERPRINT);    // SLOW BUT HASTLE-FREE METHOD FOR LONG TERM USAGE. DOES NOT REQUIRE PERIODIC UPDATE OF FINGERPRINT

void setup() {
  Serial.begin(115200);
  pinMode(led, OUTPUT);
  digitalWrite(led, LOW);
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(1000);

  // Connect to WiFi
  Serial.println();
  Serial.println();
  Serial.print("Connecting to: ");
  Serial.println(_SSID);
  WiFi.begin(_SSID, _PASSWORD);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print("-");
  }

  Serial.println("");
  Serial.println("WiFi Connected");

  // Print the IP address
  Serial.print("Use this URL to connect: ");
  Serial.print("http://");
  Serial.print(WiFi.localIP());
  Serial.println("/");
  digitalWrite(led, HIGH);

//================================================================//
//================================================================//

  // Examples of setting String, integer and float values.
  firebase.setString("Example/setString", "It's Working");
  firebase.setInt("Example/setInt", 123);
  firebase.setFloat("Example/setFloat", 45.32);

  // Examples of pushing String, integer and float values.
  firebase.pushString("push", "Hello");
  firebase.pushInt("push", 789);
  firebase.pushFloat("push", 89.54);

  // Example of getting a String.
  String data1 = firebase.getString("Example/setString");
  Serial.print("Received String: ");
  Serial.println(data1);

  // Example of getting an int.
  int data2 = firebase.getInt("Example/setInt");
  Serial.print("Received int: ");
  Serial.println(data2);

  // Example of getting a float.
  float data3 = firebase.getFloat("Example/setFloat");
  Serial.print("Received float: ");
  Serial.println(data3);

  // Example of data deletion.
  firebase.deleteData("Example");
}

void loop() {
  // Nothing
}`

The code is getting uploaded and the led is also turning on but after that I am gettting this problem

![Error Image](https://user-images.githubusercontent.com/42450202/188678266-bee55dbe-25c1-42cd-b161-0ea4616fbb4a.PNG)

`WiFi Connected
21:34:55.151 -> Use this URL to connect: http://192.168.31.69/
21:34:55.244 -> BSSL:_connectSSL: start connection
21:34:55.618 -> BSSL:CERT: 30 82 05 a0 30 82 04 88 a0 03 02 01 02 02 10 5b 32 59 c2 41 1f a4 ef 10 1d 56 e4 1c 2b 7d 80 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 46 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 22 30 20 06 03 55 04 0a 13 19 47 6f 6f 67 6c 65 20 54 72 75 73 74 20 53 65 72 76 69 63 65 73 20 4c 4c 43 31 13 30 11 06 03 55 04 03 13 0a 47 54 53 20 43 41 20 31 44 34 30 1e 17 0d 32 32 30 38 30 32 32 31 31 37 34 33 5a 17 0d 32 32 31 30 33 31 32 31 31 37 34 32 5a 30 2d 31 2b 30 29 06 03 55 04 03 0c 22 2a 2e 75 73 2d 63 65 6e 74 72 61 6c 31 2e 66 69 72 65 62 61 73 65 64 61 74 61 62 61 73 65 2e 61 70 70 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 99 54 a2 60 cb a7 8c 2b db ff 06 da 9d 92 c9 cb ab d9 58 fd 48 c2 c3 bc a6 ce 
21:34:55.711 -> BSSL:CERT: e2 19 16 09 ec d8 46 b1 7d cb c3 29 3d ca 42 71 57 df b8 e6 6b d3 f4 a3 7f be 56 6e 30 19 5a 02 2c 40 34 23 0c 32 52 5a aa 5d 4b 10 42 87 e2 af 27 48 be dc 64 da cd 05 60 15 41 d6 bb c3 4a 70 f5 aa 31 7a eb d4 f8 00 a2 73 44 f2 57 5c 5c 22 09 69 ba cb d3 a4 50 f2 46 ea 2e e6 73 31 34 fd 43 93 ab 16 3f c6 35 af 8d 21 bc ff ce 49 10 ab 73 f1 f0 8c 1c e1 ae 0a bb 26 22 f7 8f af ef fc 9c 3f a8 0c 85 3e 72 88 41 40 3e 65 03 5d f1 3e 9f f8 41 9b 16 48 77 c2 17 b7 67 12 c5 29 cc a6 62 0b cb 7e d7 20 95 f0 53 02 f8 24 2e f9 03 a3 bf ab fa 5f 98 29 b7 5a d4 7b 11 a2 7e 59 0c 6b 8b 0d e2 e0 d1 fd 65 fd ad 42 3c d1 fa d0 14 7f 0b 67 eb 6e 8e 5c 98 2f 57 3b 43 28 9a 72 eb bb f0 29 b3 ad c9 63 02 03 01 00 01 a3 82 02 a1 30 82 02 9d 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 
21:34:55.759 -> BSSL:CERT: 02 05 a0 30 13 06 03 55 1d 25 04 0c 30 0a 06 08 2b 06 01 05 05 07 03 01 30 0c 06 03 55 1d 13 01 01 ff 04 02 30 00 30 1d 06 03 55 1d 0e 04 16 04 14 12 63 9a e7 7c 4c a7 91 8d 1b f7 e0 ec 78 f1 3c dd 0b da 75 30 1f 06 03 55 1d 23 04 18 30 16 80 14 25 e2 18 0e b2 57 91 94 2a e5 d4 5d 86 90 83 de 53 b3 b8 92 30 7b 06 08 2b 06 01 05 05 07 01 01 04 6f 30 6d 30 38 06 08 2b 06 01 05 05 07 30 01 86 2c 68 74 74 70 3a 2f 2f 6f 63 73 70 2e 70 6b 69 2e 67 6f 6f 67 2f 73 2f 67 74 73 31 64 34 69 6e 74 2f 53 38 62 66 6e 61 6c 6d 43 71 73 30 31 06 08 2b 06 01 05 05 07 30 02 86 25 68 74 74 70 3a 2f 2f 70 6b 69 2e 67 6f 6f 67 2f 72 65 70 6f 2f 63 65 72 74 73 2f 67 74 73 31 64 34 2e 64 65 72 30 3f 06 03 55 1d 11 04 38 30 36 82 22 2a 2e 75 73 2d 63 65 6e 74 72 61 6c 31 2e 66 69 
21:34:55.806 -> BSSL:CERT: 72 65 62 61 73 65 64 61 74 61 62 61 73 65 2e 61 70 70 82 10 2a 2e 66 69 72 65 62 61 73 65 69 6f 2e 63 6f 6d 30 21 06 03 55 1d 20 04 1a 30 18 30 08 06 06 67 81 0c 01 02 01 30 0c 06 0a 2b 06 01 04 01 d6 79 02 05 03 30 3f 06 03 55 1d 1f 04 38 30 36 30 34 a0 32 a0 30 86 2e 68 74 74 70 3a 2f 2f 63 72 6c 73 2e 70 6b 69 2e 67 6f 6f 67 2f 67 74 73 31 64 34 69 6e 74 2f 7a 63 64 4f 30 32 62 73 69 52 41 2e 63 72 6c 30 82 01 04 06 0a 2b 06 01 04 01 d6 79 02 04 02 04 81 f5 04 81 f2 00 f0 00 76 00 46 a5 55 eb 75 fa 91 20 30 b5 a2 89 69 f4 f3 7d 11 2c 41 74 be fd 49 b8 85 ab f2 fc 70 fe 6d 47 00 00 01 82 60 a2 e9 f1 00 00 04 03 00 47 30 45 02 21 00 a9 25 11 f8 cf 0c cf 41 00 b1 58 37 68 31 f5 45 24 5b 73 25 af c6 47 8d b8 75 18 bb 13 88 5b d6 02 20 7d 5a 1a 80 f9 20 2f 0b 
21:34:55.898 -> BSSL:CERT: 2a 97 ec d9 48 39 25 bc 4f e6 21 fb 28 73 82 27 74 35 87 b8 22 e5 e3 e8 00 76 00 05 9c 01 d3 20 e0 07 84 13 95 80 49 8d 11 7c 90 32 66 af af 72 50 b5 af 3b 46 a4 3e 11 84 0d 4a 00 00 01 82 60 a2 e9 f2 00 00 04 03 00 47 30 45 02 20 38 06 b0 16 70 c1 0d a4 c2 0b 1b fd 0d 6d 9d 7f 8d 29 07 6d 21 bb a3 bb 94 d9 c6 2a 42 a8 d1 6e 02 21 00 cd ca fc c7 59 c8 6d 63 0b a8 00 37 48 c4 e3 6a aa 1b d3 d0 81 4a 73 15 08 de 9e df 6c 3d 8c d1 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 03 82 01 01 00 80 05 9b 64 1c 0b 8a 84 bd 2e c4 7f a4 68 47 3b 4f 72 6e 06 cf 95 d2 55 39 87 62 c3 97 9f c9 40 a9 f0 6d 1b 5b e0 20 53 9f f4 b1 e9 96 35 2f b7 79 a4 9a 2f d3 34 10 5b ac 6b 46 cb 95 71 28 07 23 23 27 a1 c0 00 38 ab d0 13 b4 62 f2 88 02 93 d2 a4 a0 bc 19 9b c3 e6 8c 4b cd 82 
21:34:55.944 -> BSSL:CERT: ea 72 7a cb 3a ab ce 91 14 bf 14 0f b5 b6 6b 65 f4 0c 54 ad 11 7c 61 4d 8b 31 52 48 b9 8d 59 98 1c f3 6f 8b c0 e9 74 d7 20 78 e6 74 d3 fb a4 e0 4b f5 50 30 f5 5b 46 57 fa 4f fd 09 17 73 26 b3 6f 4a 57 d6 0d c0 b8 0e 91 26 61 48 d4 b9 c4 16 f3 67 cc 90 85 03 3f af 7f ba 21 2b 2d 54 53 5f 6f 17 d1 6d 95 35 6e 40 54 dd b2 a9 42 b2 78 8b 2e 0a 42 1d 74 34 f9 f9 2a e3 fb f4 29 fa a5 fe e9 77 39 25 14 f2 e8 7b 4c 07 0d 7c 50 32 2f 48 ba 7a 2b f4 5d ea d6 f2 a1 b3 3c 94 43 d2 58 b1 46 2f fd 91 
21:34:56.973 -> BSSL:Connected!
21:34:56.973 -> BSSL:read: failed
21:34:57.017 -> BSSL:read: failed
21:34:57.017 -> BSSL:read: failed
21:34:57.017 -> BSSL:read: failed`

I am not sure what I am doing wrong

**Comment by Rupakpoddar** [comment]
This issue has been fixed in the latest version of the library.
