### ISSUE TITLE
Problem with ESP8266Firebase

### ISSUE THREAD

**Issue by AtegwuMA** [Rupakpoddar/ESP8266Firebase#6]
Please I need somebody to help me out.
I have installed ESP8266Firebase library on my Arduino IDE and have been trying to run several sketch with it without success. I kept getting this error message each time I tried to run the program. below is the error message:

 c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp: In member function 'String Firebase::setString(String, String)':
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp:40:48: error: control reaches end of non-void function [-Werror=return-type]
   40 |   String Link = String("/")+link+String(".json");
      |                                                ^
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp: In member function 'String Firebase::setNum(String, String)':
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp:79:48: error: control reaches end of non-void function [-Werror=return-type]
   79 |   String Link = String("/")+link+String(".json");
      |                                                ^
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp: In member function 'String Firebase::pushString(String, String)':
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp:107:48: error: control reaches end of non-void function [-Werror=return-type]
  107 |   String Link = String("/")+link+String(".json");
      |                                                ^
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp: In member function 'String Firebase::pushNum(String, String)':
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp:147:48: error: control reaches end of non-void function [-Werror=return-type]
  147 |   String Link = String("/")+link+String(".json");
      |                                                ^
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp: In member function 'String Firebase::deleteData(String)':
c:\Users\atem5\OneDrive\Documents\Arduino\libraries\ESP8266_Firebase\ESP8266Firebase.cpp:218:48: error: control reaches end of non-void function [-Werror=return-type]
  218 |   String Link = String("/")+link+String(".json");
      |                                                ^
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: exit status 1

**Comment by Rupakpoddar** [comment]
All issues fixed! The update was pushed to Github and Arduino IDE. The update should be available soon.
