### ISSUE TITLE
how to use this library with Arduino IoT Cloud?

### ISSUE THREAD

**Issue by L300K** [Rupakpoddar/ESP8266Firebase#7]
I tried to use this library with Arduino IoT Cloud, but it didn't work. Can you advise on how to solve it?

My Code:
```cpp
#include "arduino_secrets.h"
#include "thingProperties.h"
#include <ESP8266Firebase.h>

#define REFERENCE_URL "https://<project>.<region>.firebasedatabase.app/"

Firebase firebase(REFERENCE_URL);

void setup() {
  Serial.begin(115200);
  delay(1500); 
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  String data1 = firebase.getString("token/token");
  Serial.print("Received String:\t");
  Serial.println(data1);
}

void loop() {
  ArduinoCloud.update();
}

**Comment by Rupakpoddar** [comment]
Hi @L300K,

I wanted to let you know that this library has been deprecated and is no longer maintained. Please use the new Firebase Arduino library instead. It offers improved functionality, supports ESP8266, ESP32, Arduino UNO R4 WiFi, and is fully compatible with the Arduino Cloud IDE right out of the box.

You can find the new library here:
GitHub: https://github.com/Rupakpoddar/FirebaseArduino
Arduino Reference: https://www.arduino.cc/reference/en/libraries/firebase/

Thanks for your understanding!
